In [1]:
import importlib

from forge import *
from puzzle.puzzlepedia import prod_config, problem_widget, debug_data_widget

prod_config.init()

In [10]:
from os import path
import cv2
import numpy as np
import importlib

from data import data
from puzzle.problems import problem
from puzzle.problems.image import image_problem

def load_image(name: str) -> np.ndarray:
  return cv2.imread(image_path(name), flags=cv2.IMREAD_UNCHANGED)

def image_path(name: str) -> str:
  return path.join(data.project_path('data/grid/original'), name)


In [12]:
importlib.reload(problem)
importlib.reload(image_problem)

solve(load_image('thermo.png'))

scoring some data [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
Problem ctor
getting solutions...
_solve_iter
solving some problem
